name: Verify proxy-model.py

on: [push]

jobs:
  prepare:
    name: "Prepare images"
    runs-on: ubuntu-20.04
    env:
      SOLANA_REVISION: "v1.7.9-resources"
      EVM_LOADER_REVISION: "latest"
      SOLANA_URL: "http://solana:8899"
      PROXY_URL: "http://127.0.0.1:9090/solana"
      REVISION: ${{ github.SHA }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Pull dependency images"
        run: |
          docker pull neonlabsorg/solana:${{ env.SOLANA_REVISION }}
          docker pull neonlabsorg/evm_loader:${{ env.EVM_LOADER_REVISION }}

      - name: "Build and push proxy docker image"
        uses: docker/build-push-action@v2
        with:
#          context: .
          build-args: |
            SOLANA_REVISION=${{ env.SOLANA_REVISION }}
            EVM_LOADER_REVISION=${{ env.EVM_LOADER_REVISION }}
            PROXY_REVISION=${{ github.sha }}
          tags: |
            neonlabsorg/proxy:${{ github.sha }}

      - name: "Prepare tests"
        env:
          PROXY_IMAGE: neonlabsorg/proxy:${{ github.sha }}
          PROXY_URL: http://127.0.0.1:9090/solana
        run: |
          docker pull neonlabsorg/uniswap-v2-core:stable
          docker-compose -f proxy/docker-compose-test.yml up -d
          /bin/bash proxy/wait-proxy.sh
          echo "EVM_LOADER=$(docker exec proxy bash -c "solana address -k /spl/bin/evm_loader-keypair.json")" >> $GITHUB_ENV

      - name: "Run neon tests"
        run: docker run --rm --network=container:proxy \
               -e PROXY_URL \
               -e EVM_LOADER \
               -e SOLANA_URL \
               -e EXTRA_GAS=100000 \
               -e NEW_USER_AIRDROP_AMOUNT=100 \
               --entrypoint ./proxy/deploy-test.sh \
               neonlabsorg/proxy:${{ github.sha }}

      - name: "Run Uniswap tests"
        run: docker run --rm --network=host \
               --entrypoint ./deploy-test.sh \
               neonlabsorg/uniswap-v2-core:stable
