name: Verify proxy-model.py

on: [push]

jobs:
  prepare:
    name: "Prepare images and run tests"
    runs-on: ubuntu-20.04
    env:
      SOLANA_REVISION: "v1.7.9-resources"
      EVM_LOADER_REVISION: "latest"
      SOLANA_URL: "http://solana:8899"
      PROXY_URL: "http://127.0.0.1:9090/solana"
      REVISION: ${{ github.SHA }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Pull dependency images"
        run: |
          docker pull neonlabsorg/solana:${{ env.SOLANA_REVISION }}
          docker pull neonlabsorg/evm_loader:${{ env.EVM_LOADER_REVISION }}

      - name: "Build proxy docker image"
        uses: docker/build-push-action@v2
        with:
#          context: .
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=inline
          build-args: |
            SOLANA_REVISION=${{ env.SOLANA_REVISION }}
            EVM_LOADER_REVISION=${{ env.EVM_LOADER_REVISION }}
            PROXY_REVISION=${{ github.sha }}
          tags: |
            neonlabsorg/proxy:${{ github.sha }}

      - name: "Prepare tests"
        env:
          PROXY_IMAGE: neonlabsorg/proxy:${{ github.sha }}
          PROXY_URL: http://127.0.0.1:9090/solana
        run: |
          docker pull neonlabsorg/uniswap-v2-core:stable
          docker-compose -f proxy/docker-compose-test.yml up -d
          /bin/bash proxy/wait-proxy.sh
          echo "EVM_LOADER=$(docker exec proxy bash -c "solana address -k /spl/bin/evm_loader-keypair.json")" >> $GITHUB_ENV

      - name: "Run neon tests"
        run: |
          docker run --rm --network=container:proxy \
               -e PROXY_URL \
               -e EVM_LOADER \
               -e SOLANA_URL \
               -e EXTRA_GAS=100000 \
               -e NEW_USER_AIRDROP_AMOUNT=100 \
               --entrypoint ./proxy/deploy-test.sh \
               neonlabsorg/proxy:${{ github.sha }}

      - name: "Run Uniswap tests"
        run: |
          docker run --rm --network=host \
               --entrypoint ./deploy-test.sh \
               neonlabsorg/uniswap-v2-core:stable

      - name: "Push image"
        if: ${{ github.ref_name == 'develop' || github.ref_name == 'master' || startsWith('github.ref_name', 'ci-') || startsWith('github.ref_name', 'v')}}
        run: |
          /bin/bash proxy/publish-image.sh

      - name: "Get logs from docker"
        run: |
          docker logs proxy > proxy.log 2>&1
          grep 'get_measurements' < proxy.log > measurements.log
          docker logs solana > solana.log 2>&1
          docker logs evm_loader > evm_loader.log 2>&1

      - name: "Upload logs"
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            proxy.log
            solana.log
            measurements.log
            evm_loader.log

